###
POST http://localhost:3000/posts
Content-Type: application/json

{
    "title": "Post 1",
    "content": "Content 1",
    "sender": "owner"
}
// new post

###
GET http://localhost:3000/posts
// get all posts
###
GET http://localhost:3000/posts/6754287f7c94145c6c7f3069
// get post by id
###
GET http://localhost:3000/posts?sender=owner
// get all posts by sender
###
PUT http://localhost:3000/posts/6754287f7c94145c6c7f3069
// updates the content by id

###
DELETE http://localhost:3000/posts
// delete all posts

###
POST http://localhost:3000/posts/comments
Content-Type: application/json

{
    "content": "Comment 1",
    "sender": "owner2",
    "postId": "6754287f7c94145c6c7f3069"
}
// new comment

###
GET http://localhost:3000/posts/comments
//get all comments

###
PUT http://localhost:3000/posts/comments/675587377461a4c6e3d9dabf
// updates the comment by id

###
DELETE http://localhost:3000/posts/comments?sender=owner2
// delete all comments

###
GET http://localhost:3000/posts/comments?sender=owner2
// get all comments by sender